CREATE TABLE `usermgmt`.`user` (
  `Id` BINARY(16) NOT NULL,
  `Name` VARCHAR(200) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `Password` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE) ENGINE=InnoDB DEFAULT CHARSET=utf8;